modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="parry"
version="1.0.0"
displayName="Parry"
authors="Solven"
description="Mod for parrying any damage with keybind activation."

[[dependencies.parry]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.parry]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
